name: PR Description Generation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # push:
  #   branches:
  #     - main

jobs:
  generate_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate PR Description
        uses: rootmg93/pr-gpt
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.TOKEN }}
