name: PR Description Generation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate PR Description
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.TOKEN }}
          model: 'text-davinci-003'
          temperature: '1'
          max_tokens: '256'
          top_p: '1'
          frequency_penalty: '0'
          presence_penalty: '0'
